version: '3.8'
services:
  nginx:
    container_name: bemagro-nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php
  php:
    container_name: bemagro-php
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
  mysql:
    container_name: bemagro-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
